# Generated by Django 5.0.6 on 2024-07-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdescription',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='budget',
            field=models.CharField(blank=True, choices=[('$5 - $10 per hour', '$5 - $10 per hour'), ('$10 - $15 per hour', '$10 - $15 per hour'), ('$15 - $20 per hour', '$15 - $20 per hour'), ('$20 - $25 per hour', '$20 - $25 per hour'), ('$25 - $30 per hour', '$25 - $30 per hour'), ('$30 - $40 per hour', '$30 - $40 per hour'), ('$40 - $50 per hour', '$40 - $50 per hour')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='gender_preference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='level',
            field=models.CharField(blank=True, choices=[('Elementary', 'Elementary'), ('High School', 'High School'), ('College', 'College'), ('Professional', 'Professional')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
