# Generated by Django 5.0.6 on 2024-07-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_app', '0002_rename_content_jobdescription_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='subject',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
