# Generated by Django 5.0.6 on 2024-07-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter_app', '0003_jobdescription_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='job_posted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='lesson_time',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
