# Generated by Django 5.0.6 on 2024-07-10 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filter_app', '0004_jobdescription_job_posted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdescription',
            name='lesson_time',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='subject',
        ),
    ]
